#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'stereo-obstacle-detector','console_scripts','stereo_detector_node'
__requires__ = 'stereo-obstacle-detector'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('stereo-obstacle-detector', 'console_scripts', 'stereo_detector_node')()
    )
