#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'envision-pointcloud-to-grid','console_scripts','goal_publisher'
__requires__ = 'envision-pointcloud-to-grid'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('envision-pointcloud-to-grid', 'console_scripts', 'goal_publisher')()
    )
